#!/bin/bash
mi_home='/Users/dilanth/mitest/wso2mi-1.2.0-SNAPSHOT/'
mvn clean install
rm "$mi_home"dropins/class_mediator_1.0.0.jar || true
rm "$mi_home"lib/class_mediator.jar || true
cp '/Users/dilanth/Codes/dataweave examples/dataweave-features/ClassMediator Java/target/ClassMediatorTest-1.0-SNAPSHOT.jar' "$mi_home"lib/class_mediator.jar
